_extends: .github

repository:
  name: NucleosAllInklBundle
  description: ⚙️ This bundle provides services for using the All-Inkl API inside symfony applications
  homepage: https://nucleos.rocks
  topics: hacktoberfest, symfony, symfony-bundle, bundle, allinkl, api
